imports:
  - { resource: 'default.yml' }

# Discord
channels:
  trivia: '935081666563670069' #general channel (discord)
  verification: '935719500987396156' #verify channel (discord)

# Token
token:
  default: "hly"
  contract_address: "0x8D760497554eecC3B9036fb0364156ef2F0D02BC"
  symbol: "HLY"
  decimals: 18
  network_explorer: "https://explorer.harmony.one/#"
  rpc_url: "https://api.fuzz.fi"
  viper_pair_id: "0x3e478ED607F79A50f286A5A6ce52A049897291B2"
alternative_tokens: [ ]
tokens:
  hly:
    contract_address: "0x8D760497554eecC3B9036fb0364156ef2F0D02BC"
    symbol: "HLY"
    decimals: 18

    