imports:
  - { resource: 'default.yml' }

# Discord
channels:
  trivia: '935081722398273566'
  verification: '935081722398273566' # 919314404565188638

# Token
token:
  default: "hly"
  contract_address: "0x8D760497554eecC3B9036fb0364156ef2F0D02BC"
  symbol: "HLY"
  decimals: 18
  network_explorer: "https://explorer.harmony.one/#"
  rpc_url: "https://api.fuzz.fi"
  viper_pair_id: "0x3e478ed607f79a50f286a5a6ce52a049897291b2"
alternative_tokens:
tokens:
  hly:
    contract_address: "0x8D760497554eecC3B9036fb0364156ef2F0D02BC"
    symbol: "HLY"
    decimals: 18
