imports:
  - { resource: 'default.yml' }

# Discord
channels:
  trivia: '868080405646037013'

# Token
token:
  default: "xya"
  contract_address: "0x9b68BF4bF89c115c721105eaf6BD5164aFcc51E4"
  symbol: "XYA"
  decimals: 18
  network_explorer: "https://explorer.harmony.one/#"
  rpc_url: "https://api.harmony.one"
  viper_pair_id: "0x1485a496f816f940c510d634e48f8c66b78dc99e"
alternative_tokens:
  - yin
  - yang
tokens:
  xya:
    contract_address: "0x9b68BF4bF89c115c721105eaf6BD5164aFcc51E4"
    symbol: "XYA"
    decimals: 18
  yin:
    contract_address: "0xE59AA7f9e91B4Cc6C25D3542CEcb851e0316138c"
    symbol: "YIN"
    decimals: 18
  yang:
    contract_address: "0x340042552D19211795dbe55d84FA2E63bc49B890"
    symbol: "YANG"
    decimals: 18

# Price embed
price_embed:
  title: "Freyala | XYA"
  chart_link: "https://www.freyala.com/chart"
  url: "https://www.freyala.com/chart"
  footer: "Source: Viperswap"

# Embed
embed:
  thumbnail: "https://world.freyala.com/images/XYA.png"